#!/usr/bin/env python3
"""Generates the iOS PWA launch screens in public/splash/.

Android builds a splash automatically from the web app manifest (name,
background_color, the 512px icon). iOS does not: without
apple-touch-startup-image, launching from the home screen shows a blank white
screen until the app renders -- and this app then loads Pyodide on top of
that, so the blank stretch is long enough to look broken.

Each image must match a device's exact CSS size, pixel ratio and orientation,
so there is one file per combination. They are flat colour plus a small mark,
so each one compresses to a couple of KB.

Run manually and commit the output -- there is no image toolchain in CI, and
these only change when the branding does:

    pip install pillow
    python3 scripts/make-ios-splash.py

The <link> tags are written straight into index.html between the
ios-splash markers, so there is nothing to copy by hand and re-running is
idempotent.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "splash"

# Matches the manifest's background_color and the app's ink, so the launch
# screen and the first rendered frame are the same colour -- no flash.
BG = (250, 250, 250)
INK = (26, 26, 26)
RULE = (196, 196, 196)

WORDMARK = "PYQUESTS"
# Menlo stands in for JetBrains Mono, which isn't a system font. At this size,
# uppercase and widely tracked, they are near-indistinguishable.
FONT_PATH = "/System/Library/Fonts/Menlo.ttc"

# (css_width, css_height, device_pixel_ratio). Portrait values; landscape is
# generated by swapping. iPhones get portrait only -- nobody launches a coding
# site into landscape on a phone, and an unmatched combination simply falls
# back to today's behaviour rather than breaking.
IPHONES = [
    (320, 568, 2), (375, 667, 2), (414, 736, 3), (375, 812, 3),
    (414, 896, 2), (414, 896, 3), (390, 844, 3), (428, 926, 3),
    (393, 852, 3), (430, 932, 3), (402, 874, 3), (440, 956, 3),
]
IPADS = [
    (768, 1024, 2), (810, 1080, 2), (820, 1180, 2),
    (834, 1112, 2), (834, 1194, 2), (1024, 1366, 2),
]


def draw(css_w: int, css_h: int, ratio: int) -> Image.Image:
    w, h = css_w * ratio, css_h * ratio
    img = Image.new("RGB", (w, h), BG)
    d = ImageDraw.Draw(img)

    # Scale with the shorter edge so the mark is the same optical size on a
    # phone and on a 12.9" iPad.
    unit = min(w, h)
    font_px = max(11, round(unit * 0.046))
    font = ImageFont.truetype(FONT_PATH, font_px)
    tracking = max(1, round(font_px * 0.22))

    # Pillow has no letter-spacing, so the wordmark is drawn glyph by glyph.
    widths = [d.textlength(c, font=font) for c in WORDMARK]
    text_w = sum(widths) + tracking * (len(WORDMARK) - 1)
    ascent, descent = font.getmetrics()
    text_h = ascent + descent

    chev = round(unit * 0.034)           # the favicon's chevron
    stroke = max(2, round(unit * 0.005))
    gap = round(unit * 0.030)
    rule_w = round(text_w * 1.06)
    rule_gap = round(unit * 0.026)

    block_h = chev + gap + text_h + rule_gap + stroke
    top = (h - block_h) // 2

    # chevron ">" as two strokes, mitred
    cx, cy = w // 2, top + chev // 2
    arm = chev // 2
    d.line([(cx - arm // 2, cy - arm), (cx + arm // 2, cy)], fill=INK, width=stroke)
    d.line([(cx + arm // 2, cy), (cx - arm // 2, cy + arm)], fill=INK, width=stroke)

    x = (w - text_w) / 2
    y = top + chev + gap
    for ch, cw in zip(WORDMARK, widths):
        d.text((x, y), ch, font=font, fill=INK)
        x += cw + tracking

    ry = y + text_h + rule_gap
    d.line([((w - rule_w) // 2, ry), ((w + rule_w) // 2, ry)], fill=RULE, width=max(1, stroke // 2))
    return img


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.png"):
        f.unlink()

    links, total = [], 0
    jobs = [(w, h, r, "portrait") for (w, h, r) in IPHONES + IPADS]
    jobs += [(h, w, r, "landscape") for (w, h, r) in IPADS]

    for css_w, css_h, ratio, orient in jobs:
        name = f"splash-{css_w}x{css_h}@{ratio}x.png"
        img = draw(css_w, css_h, ratio)
        # Flat colour: a 256-colour palette is lossless here and much smaller.
        img.convert("P", palette=Image.ADAPTIVE, colors=64).save(OUT / name, optimize=True)
        total += (OUT / name).stat().st_size
        links.append(
            f'    <link rel="apple-touch-startup-image" '
            f'media="(device-width: {css_w}px) and (device-height: {css_h}px) '
            f'and (-webkit-device-pixel-ratio: {ratio}) and (orientation: {orient})" '
            f'href="/splash/{name}" />'
        )

    # Write the tags into index.html rather than leaving them for a human to
    # paste. A links.html sitting in public/ would also be copied into the
    # build and served at /splash/links.html, which is not something we want
    # to publish.
    index = ROOT / "index.html"
    html = index.read_text(encoding="utf-8")
    start, end = "<!-- ios-splash:start -->", "<!-- ios-splash:end -->"
    if start not in html or end not in html:
        raise SystemExit(
            f"index.html 에 {start} / {end} 주석이 없습니다. 먼저 넣어 주세요."
        )
    head, _, rest = html.partition(start)
    _, _, tail = rest.partition(end)
    block = "\n".join(links)
    index.write_text(f"{head}{start}\n{block}\n    {end}{tail}", encoding="utf-8")

    print(f"{len(jobs)}개 생성, 합계 {total / 1024:.0f} KB -> public/splash/")
    print(f"index.html 의 <link> 태그 {len(links)}개 갱신됨")


if __name__ == "__main__":
    main()
